(** * Macros for the definition of HILECOP Place and Transition designs. *)

Require Import NArith.
Require Import AbstractSyntax.
Require Import GlobalTypes.
Require Import HVhdlTypes.

(** /!\ We must ensure that the identifiers generated by the SITPN to
    VHDL transformation does override the set of reserved
    identifiers. Therefore, the first generated identifier must begin
    at the last reserved identifier + 1. *)

(** Defines the clock input port reserved identifier. Every design in
    H-VHDL is equipped with an clock input port.  *)

Definition clk : ident := 0.

(** Defines reserved identifiers for the place, and the transition
    designs.  *)

Definition place_entid : ident := 1.
Definition place_archid : ident := 2.
Definition transition_entid : ident := 3.
Definition transition_archid : ident := 4.

(** Reserved identifiers for the action activation and function
    execution generated processes. *)

Definition action_ps_id : ident := 5.
Definition function_ps_id : ident := 6.

(** Defines the first fresh identifier. 
    Starts the available identifier range. *)

Definition ffid : ident := 10.

(** Defines multiple macros that are convenient to build
    the Place and Transition designs in H-VHDL abstract syntax. 

    Constants, types and subtypes defined in the "petri.vhd" of HILECOP
    find here their equivalent definition in Coq.
 *)

(** Global constant macros. *)

Definition MAXIMAL_GLOBAL_MARKING : nat := 255.

(** Type and subtype macros. *)

Definition arc_t           : tind := tind_natural 0 2.
Definition transition_t    : tind := tind_natural 0 3.

Definition weight_t        : tind := tind_natural 0 MAXIMAL_GLOBAL_MARKING.
Definition weight_vector_t : expr -> expr -> tind := tind_array weight_t.
Definition arc_vector_t    : expr -> expr -> tind := tind_array arc_t.
Definition bool_vector_t   : expr -> expr -> tind := tind_array tind_boolean.

