(** * Macros for the definition of HILECOP Place and Transition designs. *)

Require Import AbstractSyntax.
Require Import GlobalTypes.

(** /!\ We must ensure that the identifiers generated by the SITPN to
    VHDL transformation does override the set of reserved
    identifiers. Therefore, the first generated identifier must begin
    at the last reserved identifier + 1. *)

(** Defines to reserved identifiers for the clock and the reset
    signals. Every design in H-VHDL are equipped with a clock and a
    reset signal, which are ports in "in" mode.

    We must enforce the fact that a H-VHDL must declare these two
    ports in its port interface; [clk] and [rst] ports must be of the
    boolean type.
 *)

Definition clk : ident := 0.
Definition rst : ident := 1.

(** Defines reserved identifiers for the place, and the transition
    designs.  *)

Definition place_entid : ident := 2.
Definition place_archid : ident := 3.
Definition transition_entid : ident := 4.
Definition transition_archid : ident := 5.

(** Reserved identifiers for variables. *)

Definition local_var : ident := 100.
Definition loop_var  : ident := 150.
Definition i : ident := loop_var.

(** Defines multiple macros that are convenient to build
    the Place and Transition designs in H-VHDL abstract syntax. 

    Constants, types and subtypes defined in the "petri.vhd" of HILECOP
    find here their equivalent definition in Coq.
 *)

(** Global constant macros. *)

Definition MAXIMAL_GLOBAL_MARKING : nat := 255.

(** Type and subtype macros. *)

Definition weight_t        : tind := tind_natural (e_nat 0, e_nat MAXIMAL_GLOBAL_MARKING).
Definition weight_vector_t : (expr * expr) -> tind := tind_array weight_t.
Definition arc_vector_t    : (expr * expr) -> tind := tind_array tind_arc_t.
Definition bool_vector_t : (expr * expr) -> tind := tind_array tind_boolean.

